# Generated by Django 3.2.18 on 2023-04-10 07:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
